export default {
  colors: {
    teal: "#50a77e",
    orange: "#e86529",
    purple: ["#d5aefb", "#c59efb", "#552e8b", "#451e7b"],
    grey: [
      "#f7fafc",
      "#edf2f7",
      "#e2e8f0",
      "#cbd5e0",
      "#a0aec0",
      "#718096",
      "#4a5568",
      "#2d3748",
      "#1a202c",
    ],
    text: "#3a3a36",
    yellow: "#f4af51",
    blue: "#001de7",
    red: "#DD3D41",
    bg: "#f7f7f3",
  },
  fonts: {
    sans: `"Source Sans Pro", -apple-system, BlinkMacSystemFont, "Segoe UI",
    "Oxygen", "Ubuntu", "Helvetica Neue", Arial, sans-serif, "Apple Color Emoji",
    "Segoe UI Emoji", "Segoe UI Symbol"`,
    serif: `"Libre Baskerville", Baskerville, Georgia, serif`,
    mono: `"IBM Plex Mono", SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace`,
  },
  pageWidth: "55vw",
};
